name: "Test"

on:
  pull_request:
    types: [synchronize, opened]

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Add pipconf
        run: |
          mkdir ~/.pip
          cat << EOF >> ~/.pip/pip.conf
          [global]
          trusted-host = pypi.fury.io
          extra-index-url = https://${{ secrets.GEMFURY_KEY }}@pypi.fury.io/ssaunier
          EOF
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install package and test
        run: |
          make pytest
